# Generated by Django 6.0.4 on 2026-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_events_even_status_idx_events_even_status_336136_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_label',
            field=models.CharField(blank=True, help_text='Override the price display text (e.g. "Free – RSVP required"). Leave blank to use the default.', max_length=100),
        ),
    ]
