# Generated by Django 6.0.4 on 2026-05-05 20:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0011_salary_indirect_activity_date_bounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfsnapshot',
            options={'get_latest_by': 'version', 'ordering': ['-generated_at'], 'verbose_name': 'PDF Snapshot', 'verbose_name_plural': 'PDF Snapshots'},
        ),
        migrations.AlterModelOptions(
            name='reportingweek',
            options={'ordering': ['start_date'], 'verbose_name': 'Reporting Week', 'verbose_name_plural': 'Reporting Weeks'},
        ),
        migrations.AlterModelOptions(
            name='weeklytimesheetline',
            options={'ordering': ['activity__sort_order', 'activity__name', 'custom_activity_name'], 'verbose_name': 'Timesheet Line', 'verbose_name_plural': 'Timesheet Lines'},
        ),
        migrations.AlterField(
            model_name='pdfsnapshot',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='periodreport',
            name='submission_type',
            field=models.CharField(choices=[('HOURS', 'Hours Based (Salary / Hourly)'), ('PCT', 'Percentage Based (Director)')], help_text='HOURS for salary/hourly (rolled up from timesheets). PCT for directors (entered directly).', max_length=5),
        ),
        migrations.AlterField(
            model_name='periodreport',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Null for PCT-based director reports.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='periodreportline',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, help_text='Auto-set to period end + 3 days at 2:00 PM. Submitted timesheets can be edited until this time.', null=True),
        ),
        migrations.AlterField(
            model_name='reportingweek',
            name='due_date',
            field=models.DateField(blank=True, help_text='Soft deadline shown to staff for this specific week.', null=True),
        ),
        migrations.AlterField(
            model_name='stafftimesheetprofile',
            name='staff_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('HOURLY', 'Hourly'), ('DIRECTOR', 'Director')], max_length=8),
        ),
    ]
