# Generated by Django 6.0.4 on 2026-05-06 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0012_alter_pdfsnapshot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periodreport',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodreport',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodreport',
            name='supervisor_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='periodreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SUPV_APPR', 'Supervisor Approved'), ('RETURNED', 'Returned'), ('PROCESSED', 'Processed')], default='DRAFT', max_length=9),
        ),
    ]
