# Generated by Django 6.0.4 on 2026-06-01 23:37

from django.db import migrations


def create_processor_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.get(app_label="timeeffort", model="stafftimesheetprofile")
    perm, _ = Permission.objects.get_or_create(
        codename="view_all_reports",
        content_type=ct,
        defaults={"name": "Can view all staff time & effort reports"},
    )
    group, _ = Group.objects.get_or_create(name="Time & Effort Processor")
    group.permissions.add(perm)


def remove_processor_group(apps, schema_editor):
    apps.get_model("auth", "Group").objects.filter(name="Time & Effort Processor").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('timeeffort', '0013_periodreport_returned'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafftimesheetprofile',
            options={'permissions': [('view_all_reports', 'Can view all staff time & effort reports')], 'verbose_name': 'Staff Timesheet Profile', 'verbose_name_plural': 'Staff Timesheet Profiles'},
        ),
        migrations.RunPython(create_processor_group, remove_processor_group),
    ]
