# Generated by Django 6.0.4 on 2026-06-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('workshop', 'Workshop'), ('lecture', 'Public Lecture'), ('event', 'Event')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Video Program',
                'verbose_name_plural': 'Video Programs',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(max_length=255)),
                ('recorded_at', models.DateTimeField()),
                ('vimeo_url', models.URLField(help_text='Full Vimeo URL, e.g. https://vimeo.com/123456789')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Ties broken by recorded date.')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='recordings.videoprogram')),
            ],
            options={
                'verbose_name': 'Recording',
                'ordering': ['order', 'recorded_at'],
            },
        ),
    ]
