# Generated by Django 6.0.4 on 2026-06-07 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_alter_program_workshop_email_description'),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogram',
            name='source_program',
            field=models.ForeignKey(blank=True, help_text='Link to the source workshop/program record. Used to pre-fill title and date.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_programs', to='programs.program'),
        ),
    ]
