# Generated by Django 6.0.4 on 2026-06-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_alter_program_workshop_email_description'),
        ('recordings', '0003_alter_videoprogram_source_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogram',
            name='vimeo_showcase_url',
            field=models.URLField(blank=True, help_text='Vimeo showcase or album URL for the full workshop (e.g. https://vimeo.com/showcase/XXXXXXX). Use this for past workshops instead of adding individual recordings.'),
        ),
        migrations.AlterField(
            model_name='videoprogram',
            name='program_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('lecture', 'Public Lecture'), ('event', 'Event')], db_index=True, default='workshop', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoprogram',
            name='source_program',
            field=models.ForeignKey(blank=True, help_text='Link to an existing workshop. Title, date, and description will be copied from it automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_programs', to='programs.workshop'),
        ),
        migrations.AlterField(
            model_name='videoprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoprogram',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
