# Generated by Django 6.0.4 on 2026-05-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_program_parent_square_alter_program_meeting_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='workshop_email_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('slot', models.CharField(choices=[('AM', 'Morning (9:00 AM)'), ('PM', 'Afternoon (2:00 PM)')], max_length=2)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Order within the slot (1, 2, 3)')),
                ('speaker_name', models.CharField(max_length=255)),
                ('speaker_institution', models.CharField(blank=True, max_length=255)),
                ('speaker_url', models.URLField(blank=True, help_text="Speaker's homepage or talk URL")),
                ('talk_title', models.CharField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='programs.program')),
            ],
            options={
                'verbose_name': 'Talk',
                'verbose_name_plural': 'Talks',
                'db_table': 'program_talk',
                'ordering': ['day', 'slot', 'order'],
            },
        ),
    ]
