# Generated by Django 6.0.4 on 2026-05-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_alter_program_workshop_email_description_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='workshop_email_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
